server:
  port: 2003
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: account_service_group

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/seata_account?allowMultiQueries=true
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: 111111

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml